---
- name: Including yaml config files based on the distribution
  include: distro_include.yml

#- name: Create local user for makepkg
#  sudo: yes
#  user: name=makepkg shell=/bin/sh

- name: Initialize GPG if never used
  command: gpg --list-key

- name: Receive xyne gpg key
  command: gpg --recv-keys 1D1F0DC78F173680

- name: Install reflector, pacserve and powerpill
  command: /usr/bin/yaourt -Sy --noconfirm reflector pacserve powerpill
  become: powerpill_yaourt_user

- name: Copy powerpill config
  sudo: yes
  template: src=templates/etc/powerpill/powerpill.j2 dest=/etc/powerpill/powerpill.json
